### ISSUE TITLE
Different data process from fb.resnet.torch

### ISSUE THREAD

**Issue by vanpersie32** [JonghwanMun/TextguidedATT#9]
Hi, Sorry to bother you, I have a little question about the code that use a different data process  method   [TextGuidedAtt](https://github.com/facebook/fb.resnet.torch/blob/master/pretrained/extract-features.lua#L90-L94) from the standard approach [fb.resnet.torch](https://github.com/facebook/fb.resnet.torch/blob/master/pretrained/extract-features.lua#L90-L94). The input image size of the code is 448x448 while the input image size of [fb.resnet.torch](https://github.com/facebook/fb.resnet.torch/blob/master/pretrained/extract-features.lua#L90-L94) is 224x224, which means that the feature map is four times as big as that of [fb.resnet.torch](https://github.com/facebook/fb.resnet.torch/blob/master/pretrained/extract-features.lua#L90-L94) . So the time for loading the feature map is very long. Could you explain why should use such a large input image size and is it possible to decrease the size of the input image without affecting the performance. Thank you very much.

**Comment by vanpersie32** [comment]
Besides, I want to know how to set the cnn_finetune_after parameter? Do you need to set it to default value -1 which means we never finetune the cnn? I think it an important parameter which makes us get as high result as you. 
Thanks.

**Comment by JonghwanMun** [comment]
1. Because the feature map size in [show, attend and tell](https://arxiv.org/pdf/1502.03044.pdf) paper is 14x14, I followed the feature map size. You can use any form of feature by revising [conv_feat_dim](https://github.com/JonghwanMun/TextguidedATT/blob/30048b6ee00a55569883d4bb90136dd6d86b15a5/001_train/resNet/train_TextguidedATT.lua#L57) as your feature channel dimmension and [feature map size (kk)](https://github.com/JonghwanMun/TextguidedATT/blob/30048b6ee00a55569883d4bb90136dd6d86b15a5/001_train/resNet/train_TextguidedATT.lua#L169) as your feature map size.
Note that if you change the feature, the performance would be different compared to our paper. Also, I think features from conv4 layer of resnet-101 given 224x224 size of images (which is 1024x14x14 feature map) would be a good alternative one.

2. Yes, I did not update CNN because most models compared with our model did not finetune the CNN part. Although I did not check whether the performance increases if the cnn_finetune_after is on, as you mentioned It would be important option to increase the performance. I think setting 10 as cnn_finetune_after would be good because there needs time to learn attention models.

**Comment by vanpersie32** [comment]
@JonghwanMun Thanks, I will try that.
